# Generated by Django 2.0.2 on 2018-06-16 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_project_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('add_projects', 'Can create new projects'),), 'verbose_name_plural': 'Projects'},
        ),
    ]
